=== RobBosman/vanace.WebItems/news/newsreader.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="NEWS_READER">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="settings_slider"/>
				<xs:element ref="settings_menu"/>
				<xs:element ref="news" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="settings_slider">
		<xs:complexType>
			<xs:attribute name="totalWidth" type="xs:short" use="required"/>
			<xs:attribute name="totalHeight" type="xs:short" use="required"/>
			<xs:attribute name="stroke2Radius" type="xs:short" use="required"/>
			<xs:attribute name="stroke2Px" type="xs:short" use="required"/>
			<xs:attribute name="stroke2Color" type="color" use="required"/>
			<xs:attribute name="stroke1Radius" type="xs:short" use="required"/>
			<xs:attribute name="stroke1Px" type="xs:short" use="required"/>
			<xs:attribute name="stroke1Color" type="color" use="required"/>
			<xs:attribute name="imageStrokePx" type="xs:short" use="required"/>
			<xs:attribute name="htmlFieldWidth" type="xs:short" use="required"/>
			<xs:attribute name="bgRadius" type="xs:short" use="required"/>
			<xs:attribute name="bgColor" type="color" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="settings_menu">
		<xs:complexType>
			<xs:attribute name="maskHeight" type="xs:short" use="required"/>
			<xs:attribute name="butHeight" type="xs:short" use="required"/>
			<xs:attribute name="butDistance" type="xs:short" use="required"/>
			<xs:attribute name="bgWidth" type="xs:short" use="required"/>
			<xs:attribute name="bgHeight" type="xs:short" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="news">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nr:description"/>
			</xs:sequence>
			<xs:attribute name="url" type="xs:anyURI" use="required"/>
			<xs:attribute name="title" type="xs:string" use="required"/>
			<xs:attribute name="date" type="date" use="required"/>
			<xs:attribute name="time" type="time" use="required"/>
			<xs:attribute name="target" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value=""/>
						<xs:enumeration value="_blank"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="picture" type="xs:anyURI" use="required"/>
			<xs:attribute name="buttonText" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="description" type="xs:string"/>
	<xs:simpleType name="color">
		<xs:restriction base="xs:string">
			<xs:pattern value="0x[0-9,A-F,a-f]{6}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="date">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]{2}\.[0-9]{2}\.[0-9]{2}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="time">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]{2}:[0-9]{2}"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== RobBosman/vanace.WebItems/advanced-news-reader-02/data.xml
<?xml version="1.0" encoding="utf-8"?>
<NEWS_READER xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="newsreader.xsd">
	<settings_slider totalWidth="479" totalHeight="191" bgColor="0x000000" stroke1Color="0x1f1f1f" stroke2Color="0x575757" bgRadius="6" stroke1Radius="6" stroke2Radius="6" stroke1Px="2" stroke2Px="1" imageStrokePx="3" htmlFieldWidth="300"/>
	<settings_menu bgWidth="457" bgHeight="23" maskHeight="123" butHeight="23" butDistance="2"/>
	<news title="Advanced News Reader 02" date="12.11.09" time="19:15" picture="images/1.jpg" buttonText="Read More" url="http://www.google.com/" target="_blank">
		<description><![CDATA[<em>Lorem ipsum dolor sit amet</em>, consectetuer adipiscing elit. Sed ante pede, semper eget, aliquet et, malesuada molestie, neque. Duis pellentesque ligula ut sem. Donec aliquam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec sollicitudin congue lectus. Fusce nec nisi vitae turpis mattis tempor. Etiam blandit dapibus nibh. Duis vehicula aliquet sem. Morbi dictum pulvinar nunc. Quisque dui arcu, Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Sed ante pede, semper eget, aliquet et, malesuada molestie, neque. Duis pellentesque ligula ut sem. Donec aliquam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec sollicitudin congue lectus. Fusce nec nisi vitae turpis mattis tempor.]]></description>
	</news>
	<news title="Party like it's not 2008: Golden Globes return" date="30.12.08" time="02:11" picture="images/2.jpg" buttonText="Read More" url="http://www.google.com/" target="_blank">
		<description><![CDATA[ Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Sed ante pede, semper eget, aliquet et, malesuada molestie, neque. Duis pellentesque ligula ut sem. Donec aliquam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec sollicitudin congue lectus. Fusce nec nisi vitae turpis mattis tempor. ]]></description>
	</news>
	<news title="News with no picture" date="30.11.08" time="02:12" picture="images/53.jpg" buttonText="" url="" target="">
		<description><![CDATA[Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Sed ante pede, semper eget, aliquet et, malesuada molestie, neque. Duis pellentesque ligula ut sem. Donec aliquam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec sollicitudin congue lectus. Fusce nec nisi vitae turpis mattis tempor. Etiam blandit dapibus nibh. Duis vehicula aliquet sem. Morbi dictum pulvinar nunc. Quisque dui arcu, Fusce nec nisi vitae turpis mattis tempor.Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Sed ante pede, semper eget, aliquet et, malesuada molestie, neque. Duis pellentesque ligula ut sem. Donec aliquam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec sollicitudin congue lectus. Fusce nec nisi vitae turpis mattis tempor. Etiam blandit dapibus nibh. Duis vehicula aliquet sem. Morbi dictum pulvinar nunc. Quisque dui arcu, Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Sed ante pede, semper eget, aliquet et, malesuada molestie, neque. Duis pellentesque ligula ut sem. Donec aliquam.]]></description>
	</news>
	<news title="Lawmakers, Muslims criticize prince over comments" date="03.09.08" time="11:20" picture="images/4.jpg" buttonText="Read More" url="http://www.google.com/" target="_blank">
		<description><![CDATA[ orem ipsum dolor sit amet, consectetuer adipiscing elit. Sed ante pede, semper eget, aliquet et, malesuada molestie, neque. Duis pellentesque ligula ut sem. Donec aliquam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec sollicitudin congue lectus. Fusce nec nisi vitae turpis mattis tempor. Etiam blandit dapibus nibh. Duis vehicula aliquet sem. Morbi dictum pulvinar nunc. Quisque dui arcu, Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Sed ante pede, semper eget, aliquet et, malesuada molestie, neque. Duis pellentesque ligula ut sem. Donec aliquam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec sollicitudin congue lectus. Fusce nec nisi vitae turpis mattis tempor.Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Sed ante pede, semper eget, aliquet et, malesuada molestie, neque. Duis pellentesque ligula ut sem. Donec aliquam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec sollicitudin congue lectus. Fusce nec nisi vitae turpis mattis tempor. Etiam blandit dapibus nibh. Duis vehicula aliquet sem. Morbi dictum pulvinar nunc. Quisque dui arcu, Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Sed ante pede, semper eget, aliquet et, malesuada molestie, neque. Duis pellentesque ligula ut sem. Donec aliquam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec sollicitudin congue lectus. Fusce nec nisi vitae turpis mattis tempor.Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Sed ante pede, semper eget, aliquet et, malesuada molestie, neque. Duis pellentesque ligula ut sem. Donec aliquam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec sollicitudin congue lectus. Fusce nec nisi vitae turpis mattis tempor. Etiam blandit dapibus nibh. Duis vehicula aliquet sem.]]></description>
	</news>
	<news title="Snowstorm ices roads" date="05.01.09" time="02:12" picture="images/5.jpg" buttonText="Read More" url="http://www.google.com/" target="_blank">
		<description><![CDATA[ Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Sed ante pede, semper eget, aliquet et, malesuada molestie, neque. Duis pellentesque ligula ut sem. Donec aliquam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. ]]></description>
	</news>
	<news title="Cardinals stun Panthers" date="12.11.09" time="19:15" picture="images/6.jpg" buttonText="Read More" url="http://www.google.com/" target="_blank">
		<description><![CDATA[ Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Sed ante pede, semper eget, aliquet et, malesuada molestie, neque. Duis pellentesque ligula ut sem. Donec aliquam. Cum sociis natoque penatibus et magnis dis parturient montes, amet, consectetuer adipiscing elit. Sed ante pede, semper eget, aliquet et, malesuada molestie, neque. Duis pellentesque ligula ut sem. Donec aliquam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.  vestibulum. Praesent consectetuer augue nec risus. Etiam sollicitudin congue purus. Nullam velit leo, dignissim ac, blandit quis, volutpat at, velit. Suspendisse iaculis pellentesque dolor. Duis risus quam, aliquet eget, volutpat non, porttitor sed, sapien. Suspendisse potenti. Donec semper, elit quis malesuada]]></description>
	</news>
	<news title="Wild-card Ravens, rookie" date="12.10.09" time="19:15" picture="images/1.jpg" buttonText="Read More" url="http://www.google.com/" target="_blank">
		<description><![CDATA[ Lorem ipsum dolor sit amet, consectetuer adipiscin Nullam vestibulum. Praesent consectetuer augue nec risus. Etiam sollicitudin congue purus. Nullam velit leo, dignissim ac, blandit quis, volutpat at, velit. Suspendisse iaculis pellentesque dolor. Duis risus quam, aliquet eget, volutpat non, porttitor sed, sapien. Suspendisse potenti. Donec semper, elit quis malesuada]]></description>
	</news>
	<news title="Obama: $350b bailout needs to help people" date="12.11.09" time="19:15" picture="images/2.jpg" buttonText="Read More" url="http://www.google.com/" target="_blank">
		<description><![CDATA[ Lorem ipsum dolor sit amet, consectetuer adipiscinet, aliquet et, malesuada molestie, neque. Duis pellentesque ligula ut sem. Donec aliquam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec sollicitudin congue lectus. Fusce nec nisi vitae turpis mattis tempor. Etiam blandit dapibus nibh. Duis vehicula aliquet sem. Morbi dictum pulvinar nunc. Quisque dui arcu, euismod imperdiet, tincidunt ac, commodo imperdiet, mauris.lam vestibulum. Praesent consectetuer augue nec risus. Etiam sollicitudin congue purus. Nullam velit leo, dignissim ac, blandit quis, volutpat at, velit. Suspendisse iaculis pellentesque dolor. Duis risus quam, aliquet eget, volutpat non, porttitor sed, sapien. Suspendisse potenti. Donec semper, elit quis malesuada]]></description>
	</news>
	<news title="Senate to consider expanding wilderness protection" date="12.11.09" time="19:15" picture="images/3.jpg" buttonText="Read More" url="http://www.google.com/" target="_blank">
		<description><![CDATA[ Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Sed ante pede, semper eget, aliquet et, malesuada molestie, neque. Duis pellentesque ligula ut sem. Donec aliquam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec sollicitudin congue lectus. Fusce nec nisi vitae turpis mattis tempor. Etiam blandit dapibus nibh. Duis vehicula aliquet sem. Morbi dictum pulvinar nunc. Quisque dui arcu, euismod imperdiet, tincidunt ac, coliquet eget, volutpat non, porttitor sed, sapien. Suspendisse potenti. Donec semper, elit quis malesuadaMorbi dictum pulvinar nunc. Quisque dui arcu, euismod imperdiet, tincidunt ac, commodo imperdiet, mauris.
Phasellus porttitor mauris ac felis. Vestibulum quis dui a dui hendrerit blandit. Nullam vestibulum. Praesent consectetuer augue nec risus. Etiam sollicitudin congue purus. Nullam velit leo, dignissim ac, blandit quis, volutpat at, velit. Suspendisse iaculis pellentesque dolor. Duis risus quam, aliquet eget, volutpat non, porttitor sed, sapien. Suspendisse potenti. Donec semper, elit quis malesuada
